input_files:
  source: "generic-pancreas-organ.glb"

target_name: "https://purl.humanatlas.io/ref-organ/pancreas-male/v1.3#primary"

donor:
  sex: Male
  provider_name: MC-IU
  provider_uuid: 87751d4c-a850-4e2c-84dc-da6a797d76de
  consortium_name: HRA
  id: "https://purl.humanatlas.io/millitome/pancreas-male-uf/v1.0"
  selected-organ: "http://purl.obolibrary.org/obo/UBERON_0001264"

rui_location:
  "@context": "https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld"
  "@type": "SpatialEntity"
  creator: "Antara Bhavsar"
  creator_first_name: "Antara"
  creator_last_name: "Bhavsar"
  creator_orcid: "https://orcid.org/0009-0006-6491-6503"
  dimension_units: "millimeter"
  placement:
    "@context": "https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld"
    "@type": "SpatialPlacement"
    target: "https://purl.humanatlas.io/ref-organ/pancreas-male/v1.3#primary"
    scaling_units: "ratio"
    rotation_order: "XYZ"
    rotation_units: "degree"
    translation_units: "millimeter"

nonrigid_registration:
  autotune: 'False'
  gamma: 6
  beta: 1
  decimation: 'False'
  distance_threshold: 1e-8
  lambda: 10
  downsampling: 'Y, 26443, 0.05'
  max_iterations: 1000
  seed: 26

rigid_registration:
  global_distance_threshold_factor: 0.23
  global_edge_length_threshold_factor: 0.95
  global_max_correspondence: 0.999
  global_max_iterations: 100000
  max_nn: 100
  refine_distance_threshold_factor: 0.1
  voxel_size: 0.025

fused-blocks:
  "1" : ['1A','1B','1C','1D']
  "2" : ['2A','2B','2C','2D']
  "3" : ['3A','3B','3C','3D']
  "4" : ['4A','4B','4C','4D']
  "5" : ['5A','5B','5C','5D']
  "6" : ['6A','6B','6C','6D']
  "7" : ['7A','7B','7C','7D']
  "8" : ['8A','8B','8C','8D']
  "9" : ['9A','9B','9C','9D']
  "10" : ['10A','10B','10C','10D']
  "11" : ['11A','11B','11C','11D']
  "12" : ['12A','12B','12C','12D']
  "13" : ['13A','13B','13C','13D']
  "14" : ['14A','14B','14C','14D']
  "15" : ['15A','15B','15C','15D']
  "16" : ['16A','16B','16C','16D']
  "17" : ['17A','17B','17C','17D']
  "18" : ['18A','18B','18C','18D']
  "19" : ['19A','19B','19C','19D']
  "20" : ['20A','20B','20C','20D']
  "21" : ['21A','21B','21C','21D']
  "22" : ['22A','22B','22C','22D']
  "23" : ['23A','23B','23C','23D']
  "24" : ['24A','24B','24C','24D']
