input_files:
  source: "kidney-right-vu500.glb"

retain_component: ["VH_M_kidney_capsule_R"]

target_name: "https://purl.humanatlas.io/ref-organ/kidney-male-right/v1.3#primary"

visual_hull:
  target_grid: 120
  image_size: 420
  force_rebuild: false

allowed_targets:
  - "https://purl.humanatlas.io/ref-organ/kidney-male-right/v1.3#primary"
  - "http://purl.org/ccf/latest/ccf.owl#VHMRightKidney"

donor:
  sex: Male
  provider_name: MC-IU
  provider_uuid: 87751d4c-a850-4e2c-84dc-da6a797d76de
  consortium_name: HRA
  id: "https://purl.humanatlas.io/millitome/kidney-male-right-vu/v1.0"
  selected-organ: "http://purl.obolibrary.org/obo/UBERON_0004539"

rui_location:
  "@context": "https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld"
  "@type": "SpatialEntity"
  creator: "Antara Bhavsar"
  creator_first_name: "Antara"
  creator_last_name: "Bhavsar"
  creator_orcid: "https://orcid.org/0009-0006-6491-6503"
  dimension_units: "millimeter"
  placement:
    "@context": "https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld"
    "@type": "SpatialPlacement"
    target: "https://purl.humanatlas.io/ref-organ/kidney-male-right/v1.3#primary"
    scaling_units: "ratio"
    rotation_order: "XYZ"
    rotation_units: "degree"
    translation_units: "millimeter"

nonrigid_registration:
  autotune: 'False'
  gamma: 0.1
  beta: 0.8
  decimation: 'False'
  distance_threshold: 1.0e-06
  lambda: 140
  downsampling: 'X,60000,0.05,Y,60000,0.05'
  max_iterations: 300
  seed: 1

rigid_registration:
  global_distance_threshold_factor: 0.23
  global_edge_length_threshold_factor: 0.95
  global_max_correspondence: 0.999
  global_max_iterations: 100000
  max_nn: 100
  refine_distance_threshold_factor: 0.1
  voxel_size: 0.025
