VHFPancreas:
  scaling: 
    - 1.0
    - 1.0
    - 1.0
  rotation: 
    - 0
    - 0 
    - 0
  translation: 
    - 53.9812557
    - -237.53333099999998
    - 112.085223

VHMPancreas:
  scaling: 
    - 1.0
    - 1.0
    - 1.0
  rotation: 
    - 0
    - 0 
    - 0
  translation: 
    - 33.9610465
    - -303.56636599999996
    - 32.6540545

VHFLeftKidneyV1.1:
  scaling: 
    - 1.0
    - 1.0
    - 1.0
  rotation: 
    - 0
    - 0 
    - 0
  translation: 
    - -40.05157
    - -175.776139
    - 139.386386

VHFRightKidneyV1.1:
  scaling: 
    - 1.0
    - 1.0
    - 1.0
  rotation: 
    - 0
    - 0 
    - 0
  translation: 
    x: 108.721532
    y: -198.595762
    z: 134.438053

VHMLeftKidney:
  scaling: 
    - 1.0
    - 1.0
    - 1.0
  rotation: 
    - 0
    - 0 
    - 0
  translation: 
    - -33.7257273
    - -249.827653
    - 68.65017

VHMRightKidney:
  scaling: 
    - 1.0
    - 1.0
    - 1.0
  rotation: 
    - 0
    - 0 
    - 0
  translation: 
    - 96.93149
    - -229.012564
    - 51.3739847
