VHFLeftFallopianTube:
  scaling: 
    - 1.0
    - 1.0
    - 1.0
  rotation: 
    - 0
    - 0 
    - 0
  translation: 
    - -12.0652765
    - -40.887355799999995
    - 52.033919999999995

VHFRightFallopianTube:
  scaling: 
    - 1.0
    - 1.0
    - 1.0
  rotation: 
    - 0
    - 0 
    - 0
  translation: 
    - 73.73370999999999
    - -39.8927853
    - 57.979620000000004

VHFUterus:
  scaling: 
    - 1.0
    - 1.0
    - 1.0
  rotation: 
    - 0
    - 0 
    - 0
  translation: 
    - 39.745044
    - -6.2188454900000005
    - 86.19217

VHFLeftOvary:
  scaling: 
    - 1.0
    - 1.0
    - 1.0
  rotation: 
    - 0
    - 0 
    - 0
  translation: 
    - -38.216304
    - -48.9767827
    - 50.7369228

VHFRightOvary:
  scaling: 
    - 1.0
    - 1.0
    - 1.0
  rotation: 
    - 0
    - 0 
    - 0
  translation: 
    - 76.71706999999999
    - -48.90892
    - 50.8165732

VHFPancreas:
  scaling: 
    - 1.0
    - 1.0
    - 1.0
  rotation: 
    - 0
    - 0 
    - 0
  translation: 
    - 53.9812557
    - -237.53333099999998
    - 112.085223

VHMPancreas:
  scaling: 
    - 1.0
    - 1.0
    - 1.0
  rotation: 
    - 0
    - 0 
    - 0
  translation: 
    - 33.9610465
    - -303.56636599999996
    - 32.6540545

VHFLeftKidneyV1.1:
  scaling: 
    - 1.0
    - 1.0
    - 1.0
  rotation: 
    - 0
    - 0 
    - 0
  translation: 
    - -40.05157
    - -175.776139
    - 139.386386

VHFRightKidneyV1.1:
  scaling: 
    - 1.0
    - 1.0
    - 1.0
  rotation: 
    - 0
    - 0 
    - 0
  translation: 
    - 108.721532
    - -198.595762
    - 134.438053

VHMLeftKidney:
  scaling: 
    - 1.0
    - 1.0
    - 1.0
  rotation: 
    - 0
    - 0 
    - 0
  translation: 
    - -33.7257273
    - -249.827653
    - 68.65017

VHMRightKidney:
  scaling: 
    - 1.0
    - 1.0
    - 1.0
  rotation: 
    - 0
    - 0 
    - 0
  translation: 
    - 96.93149
    - -229.012564
    - 51.3739847
