nonrigid_registration:
  autotune: 'False'
  beta: 0.5
  decimation: 'False'
  distance_threshold: 1e-8
  lambda: 50
  max_iterations: 1000
  seed: 26
rigid_registration:
  global_distance_threshold_factor: 0.23
  global_edge_length_threshold_factor: 0.95
  global_max_correspondence: 0.999
  global_max_iterations: 100000
  max_nn: 100
  refine_distance_threshold_factor: 0.1
  voxel_size: 0.025
