pancreas-female-vu:
    raw_data_path: "raw-data/millitome/pancreas-female-vu/v1.0"
    output_path: "output-data/millitome/pancreas-female-vu/v1.0"
    config_path: "input-data/millitome/pancreas-female-vu/v1.0/config.yaml"

pancreas-male-vu:
    raw_data_path: "raw-data/millitome/pancreas-male-vu/v1.0"
    output_path: "output-data/millitome/pancreas-male-vu/v1.0"
    config_path: "input-data/millitome/pancreas-male-vu/v1.0/config.yaml"